#KomplexKanban-V3

The goal of this project is to create a complex numbers class and mathematical operators to manipulate them.
## Getting Started

This project is about creating the operators for a new, unfamiliar object. To complete it, you must create the operators and tests for 22 operators. See deployment for notes on how to deploy the project on a live system.

### Prerequisites
You will need to have a catch_amalgamated file already provided 
```
catch_amalgamated.cpp
```

### Installing

First, you ought to download the zip file. unzip it into a directory. add the directory to your PATH variable.

```
cd /usr/local/bin/
unzip KomplexKanban.zip
export PATH=$PWD:/usr/local/bin
```

And repeat

```
until finished
```

End with an example of getting some data out of the system or using it for a little demo

## Running the tests

from the shell, type the "make" command to see the tests

### Break down into end to end tests

these tests will prompt the operators with example input and the correct output. If they are equal, the test will pass; else, they fail.
```
Complex(2,1)+Complex(1,1) == Complex(3,2)
```

### And coding style tests

the tests are testing the accuracy of your operators based on known values
```
Complex(2,1)+Complex(1,1) == Complex(3,2)
```

## Deployment

download the package, export it as a zip, and run it on whatever platform you prefer.

## Built With

* [GNU Tools](https://www.gnu.org/software/gcc/) - GNU compiler tools
* Any other tools ....


## Structure
``` text
.
├── CMakeLists.txt
├── app
│   └── main.cpp
├── include
│   ├── example.h
│   └── exampleConfig.h.in
├── src
│   └── example.cpp
└── tests
    ├── dummy.cpp
    └── main.cpp
```
The directory tree can be generated by the linux **tree** command.  You may need to add this to the REPL NIX environment (install tree.out).

Sources go in [src/](src/), header files in [include/](include/), main programs in [app/](app), and
tests go in [tests/](tests/) (compiled to `unit_tests` by default).

If you add a new executable, say `app/hello.cpp`, you only need to add the following two lines to [CMakeLists.txt](CMakeLists.txt):

```cmake
add_executable(main app/main.cpp)   # Name of exec. and location of file.
target_link_libraries(main PRIVATE ${LIBRARY_NAME})  # Link the executable to lib built from src/*.cpp (if it uses it).
```

You can find the example source code that builds the `main` executable in [app/main.cpp](app/main.cpp) under the `Build` section in [CMakeLists.txt](CMakeLists.txt).
If the executable you made does not use the library in [src/](src), then only the first line is needed.



## Building

Build by making a build directory (i.e. `build/`), run `cmake` in that dir, and then use `make` to build the desired target.

Example:

```bash
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=[Debug | Coverage | Release]
make
./main
make test      # Makes and runs the tests.
make coverage  # Generate a coverage report.
make doc       # Generate html documentation.
```

## .gitignore

The [.gitignore](.gitignore) file is a copy of the [Github C++.gitignore file](https://github.com/github/gitignore/blob/master/C%2B%2B.gitignore),
with the addition of ignoring the build directory (`build/`).



## Contributing

Please read [CONTRIBUTING.md](https://gist.github.com/PurpleBooth/b24679402957c63ec426) for details on our code of conduct, and the process for submitting pull requests to us.

## Versioning

We use [SemVer](http://semver.org/) for versioning. For the versions available, see the [tags on this repository](https://github.com/your/project/tags). 

## Authors

* **Billie Thompson** - *Initial work* - [PurpleBooth](https://github.com/PurpleBooth)

See also the list of [contributors](https://github.com/your/project/contributors) who participated in this project.

## License

This project is licensed under the MIT License - see the [LICENSE.md](LICENSE.md) file for details

## Acknowledgments

* Thank you Mr. Shockey for the template for this README
* THank you for my teammates for helping with running my code and committing it to GitHub
